import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  competency: {
    color: '#272728',
    fontSize: '10px',
    fontWeight: 'semibold',
    marginBottom: '12px',
  },
  levelContainer: {
    margin: '0px 3px 0px 12px',
  },
  TableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tableHeaderText: {
    fontSize: '9px',
    fontWeight: 'bold',
  },
  levelChart: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: '5px',
  },
  logText: {
    fontSize: '9px',
    color: '#272728',
    fontWeight: 600,
    marginTop: '12px',
  },
  logsList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: '10px 0px',
  },
  listTextNo: {
    fontSize: '9px',
    fontWeight: 400,
    color: '#272728',
  },
  listText: {
    fontSize: '9px',
    fontWeight: 400,
    color: '#272728',
    width: '85%',
    textAlign: 'justify',
  },

  listTextFlex: {
    flexDirection: 'row',
    gap: '5px',
  },
  logsDate: {
    color: '#65758C',
    fontSize: '9px',
    fontWeight: 400,
    marginTop: '5px',
  },
  listPercentageContainer: {
    textAlign: 'center',
    width: '40px',
  },
  listPercentage: {
    color: 'black',
    fontSize: '9px',
    fontWeight: 500,
  },
  compassIcon: {
    textAlign: 'center',
    fontSize: '19px',
    paddingTop: '13px',
    color: '#65758C',
    fontWeight: 600,
  },
  pdfViewer: {
    width: '100%',
    height: '1000px',
  },
  pageCss: {
    padding: '12px 16px',
  },
  headingText: {
    textAlign: 'center',
    fontSize: '14px',
    marginBottom: '9px',
    color: '#272728',
    fontWeight: 600,
  },
  headingBorder: {
    borderBottom: '2px solid #385B8B',
    marginBottom: '3px',
  },
  overAllCompassContainer: {
    border: '1px solid #FFE073',
    backgroundColor: '#FFF7DA',
    borderRadius: '5px',
    height: 'auto',
    padding: '6px 10px',
    marginBottom: '12px',
  },
  overAllCompassText: {
    fontSize: '9px',
    fontWeight: 500,
    color: '#272728',
    marginBottom: '8px',
  },
  dataAndPercentageContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  percentageText: {
    color: '#385B8B',
    fontSize: '15px',
    fontWeight: 700,
  },
  aggregateText: {
    color: '#385B8B',
    fontSize: '9px',
    fontWeight: 400,
    backgroundColor: '#BEE8FF',
    padding: '0px 5px',
    borderRadius: '5px',
    height: '15px',
    width: '65px',
  },
  percentageContainer: {
    flexDirection: 'row',
    gap: '10px',
  },
  dateContainer: {
    color: '#787878',
    fontSize: '9px',
    fontWeight: 400,
    textAlign: 'right',
  },
  rightAlignText: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: '3px 0px',
  },
  competencyHeading: {
    color: '#272728',
    fontSize: '13px',
    fontWeight: 600,
    marginBottom: '10px',
  },
  assessmentTypes: {
    flexDirection: 'row',
    gap: '30px',
    marginBottom: '15px',
  },
  svgContainer: {
    flexDirection: 'row',
    gap: '5px',
    color: '#65758C',
    fontSize: '9px',
    fontWeight: 400,
  },
  level1: {
    width: '53px',
    fontSize: '8px',
    color: '#2D2D2D',
    backgroundColor: '#7CE780',
    fontWeight: 500,
    padding: '3px 0px',
    textAlign: 'center',
    height: '16px',
    border: '1px solid #E1E1E1',
  },
  level2: {
    width: '53px',
    fontSize: '8px',
    color: '#2D2D2D',
    backgroundColor: '#F8DA72',
    fontWeight: 500,
    padding: '3px 0px',
    textAlign: 'center',
    height: '16px',
    border: '1px solid #E1E1E1',
  },
  level3: {
    width: '53px',
    fontSize: '8px',
    color: '#2D2D2D',
    backgroundColor: '#FF9F46',
    fontWeight: 500,
    padding: '3px 0px',
    textAlign: 'center',
    height: '16px',
    border: '1px solid #E1E1E1',
  },
  level4: {
    width: '53px',
    fontSize: '8px',
    color: '#2D2D2D',
    backgroundColor: '#D8D8D8',
    fontWeight: 500,
    padding: '3px 0px',
    textAlign: 'center',
    height: '16px',
    border: '1px solid #E1E1E1',
  },
});
