version: '3'

services:
  passbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true
